### ISSUE TITLE
Add emoji to ingredient

### ISSUE THREAD

**Issue by nicholaswilde** [nicholaswilde/cook-docs#11]
Add emoji to the front of each ingredient depending on ingredient type.

This may be specified in the `.cookdocs.yaml` config file.

```yaml
...
emoji:
  herb:
    - cilantro
...
```

```markdown
....
## Ingredients

- :herb: 1 Tbsp celantro
...
```
